import type { Metadata } from "next"
import { Mulish } from "next/font/google"
import "./globals.css"
import TickitzProvider from "@/context/TickitzProvider"
import { Toaster } from "@/components/ui/toaster"

const mulish = Mulish({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={mulish.className}>
        <TickitzProvider>{children}</TickitzProvider>
        <Toaster />
      </body>
    </html>
  )
}
