import type { Metadata } from "next"
import { Mulish } from "next/font/google"
import "./globals.css"
import TickitzProvider from "@/context/TickitzProvider"
import { Toaster } from "@/components/ui/toaster"
import { auth } from "@/auth"
import { SessionProvider } from "next-auth/react"
const mulish = Mulish({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Tickitz",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang='en'>
      <body className={mulish.className}>
        <SessionProvider session={session}>
          <TickitzProvider>{children}</TickitzProvider>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  )
}
