export const cities = [
  {
    city_id: "170",
    province_id: "1",
    province: "Bali",
    type: "Kabupaten",
    city_name: "Karangasem",
    postal_code: "80819",
  },
  {
    city_id: "171",
    province_id: "9",
    province: "Jawa Barat",
    type: "Kabupaten",
    city_name: "Karawang",
    postal_code: "41311",
  },
  {
    city_id: "172",
    province_id: "17",
    province: "Kepulauan Riau",
    type: "Kabupaten",
    city_name: "Karimun",
    postal_code: "29611",
  },
  {
    city_id: "173",
    province_id: "34",
    province: "Sumatera Utara",
    type: "Kabupaten",
    city_name: "Karo",
    postal_code: "22119",
  },
  {
    city_id: "174",
    province_id: "14",
    province: "Kalimantan Tengah",
    type: "Kabupaten",
    city_name: "Katingan",
    postal_code: "74411",
  },
  {
    city_id: "175",
    province_id: "4",
    province: "Bengkulu",
    type: "Kabupaten",
    city_name: "Kaur",
    postal_code: "38911",
  },
  {
    city_id: "176",
    province_id: "12",
    province: "Kalimantan Barat",
    type: "Kabupaten",
    city_name: "Kayong Utara",
    postal_code: "78852",
  },
  {
    city_id: "177",
    province_id: "10",
    province: "Jawa Tengah",
    type: "Kabupaten",
    city_name: "Kebumen",
    postal_code: "54319",
  },
  {
    city_id: "178",
    province_id: "11",
    province: "Jawa Timur",
    type: "Kabupaten",
    city_name: "Kediri",
    postal_code: "64184",
  },
  {
    city_id: "179",
    province_id: "11",
    province: "Jawa Timur",
    type: "Kota",
    city_name: "Kediri",
    postal_code: "64125",
  },
  {
    city_id: "180",
    province_id: "24",
    province: "Papua",
    type: "Kabupaten",
    city_name: "Keerom",
    postal_code: "99461",
  },
  {
    city_id: "181",
    province_id: "10",
    province: "Jawa Tengah",
    type: "Kabupaten",
    city_name: "Kendal",
    postal_code: "51314",
  },
  {
    city_id: "182",
    province_id: "30",
    province: "Sulawesi Tenggara",
    type: "Kota",
    city_name: "Kendari",
    postal_code: "93126",
  },
  {
    city_id: "183",
    province_id: "4",
    province: "Bengkulu",
    type: "Kabupaten",
    city_name: "Kepahiang",
    postal_code: "39319",
  },
  {
    city_id: "184",
    province_id: "17",
    province: "Kepulauan Riau",
    type: "Kabupaten",
    city_name: "Kepulauan Anambas",
    postal_code: "29991",
  },
  {
    city_id: "185",
    province_id: "19",
    province: "Maluku",
    type: "Kabupaten",
    city_name: "Kepulauan Aru",
    postal_code: "97681",
  },
  {
    city_id: "186",
    province_id: "32",
    province: "Sumatera Barat",
    type: "Kabupaten",
    city_name: "Kepulauan Mentawai",
    postal_code: "25771",
  },
  {
    city_id: "187",
    province_id: "26",
    province: "Riau",
    type: "Kabupaten",
    city_name: "Kepulauan Meranti",
    postal_code: "28791",
  },
  {
    city_id: "188",
    province_id: "31",
    province: "Sulawesi Utara",
    type: "Kabupaten",
    city_name: "Kepulauan Sangihe",
    postal_code: "95819",
  },
  {
    city_id: "189",
    province_id: "6",
    province: "DKI Jakarta",
    type: "Kabupaten",
    city_name: "Kepulauan Seribu",
    postal_code: "14550",
  },
  {
    city_id: "191",
    province_id: "20",
    province: "Maluku Utara",
    type: "Kabupaten",
    city_name: "Kepulauan Sula",
    postal_code: "97995",
  },
  {
    city_id: "192",
    province_id: "31",
    province: "Sulawesi Utara",
    type: "Kabupaten",
    city_name: "Kepulauan Talaud",
    postal_code: "95885",
  },
  {
    city_id: "194",
    province_id: "8",
    province: "Jambi",
    type: "Kabupaten",
    city_name: "Kerinci",
    postal_code: "37167",
  },
  {
    city_id: "501",
    province_id: "5",
    province: "DI Yogyakarta",
    type: "Kota",
    city_name: "Yogyakarta",
    postal_code: "55111",
  },
]
